databases:
  - name: cnc-pwa_db
    region: singapore
    plan: free
    databaseName: cnc-pwa_db
    user: django_user

services:
  - type: redis
    name: cnc-pwa-redis
    region: singapore
    plan: free
    maxmemoryPolicy: allkeys-lfu

  - type: web
    name: cnc-pwa
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'daphne -b 0.0.0.0 -p 10000 cnc-pwa.asgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: cnc-pwa_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: cnc-pwa-redis
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true
